### PR TITLE
Added icons to context menu

### PR DESCRIPTION
**Pull request by kstenschke**
Hi mikinw and thank you for this helpful plugin,
please consider merging the changes from my pull request: 
i added icons to the context menu group and its items.

Greeetings, Kay

### CODE REVIEW

**Comment by mikinw** [comment]
Sorry, I didn't expect anyone would create pull requests, but I'm glad I was wrong. :-)
I'll review it soon

**Comment by kstenschke** [comment]
no problem. please note: only after creating the pull request, i discovered that there are plugin settings and that the marker colors are dynamic- the (static) icons therefor are only valid for the default colors.

**Comment by mikinw** [comment]
Yes. However if I can generate and set the icons from code, that could be a good feature.

**Comment by mikinw** [comment]
After this many years ( :-) ) I have updated the plugin. It now has colour icons for the action. (And also has a bunch of new features.)

**Pull request closed without merging**
